/// Flutter icons C17Frontal
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  C17Frontal
///      fonts:
///       - asset: fonts/C17Frontal.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class C17Frontal {
  C17Frontal._();

  static const _kFontFam = 'C17Frontal';
  static const String? _kFontPkg = null;

  static const IconData c17_frontal_square_windows =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
