// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-15_zWHnrHTkZMOG_cF9ivwpO0yPrneo',
    appId: '1:133332829439:web:036803e7ee123568f2b8ca',
    messagingSenderId: '133332829439',
    projectId: 'smartspacea-c8225',
    authDomain: 'smartspacea-c8225.firebaseapp.com',
    storageBucket: 'smartspacea-c8225.appspot.com',
    measurementId: 'G-W8SLYVS2DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEpMIiKV3kNRg5DL5xUWiq5WSiMUQH-Qg',
    appId: '1:133332829439:android:1198909073f9f312f2b8ca',
    messagingSenderId: '133332829439',
    projectId: 'smartspacea-c8225',
    storageBucket: 'smartspacea-c8225.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWRG-JcC1UhM58zZZojlmiByTR6ZluDgA',
    appId: '1:133332829439:ios:8c6240074fcb990bf2b8ca',
    messagingSenderId: '133332829439',
    projectId: 'smartspacea-c8225',
    storageBucket: 'smartspacea-c8225.appspot.com',
    iosBundleId: 'com.example.ssaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWRG-JcC1UhM58zZZojlmiByTR6ZluDgA',
    appId: '1:133332829439:ios:d74c4e0b7bea6b5ef2b8ca',
    messagingSenderId: '133332829439',
    projectId: 'smartspacea-c8225',
    storageBucket: 'smartspacea-c8225.appspot.com',
    iosBundleId: 'com.example.ssaApp.RunnerTests',
  );
}
